OperationalError
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)

Traceback (most recent call last)
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
self._dbapi_connection = engine.raw_connection()
                         ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3297, in raw_connection
return self.pool.connect()
       ^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
return _ConnectionFairy._checkout(self)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout
fairy = _ConnectionRecord.checkout(pool)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 713, in checkout
rec = pool._do_get()
      ^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
with util.safe_reraise():
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
raise exc_value.with_traceback(exc_tb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
                    code="3o7r",
                )
 
        if self._inc_overflow():
            try:
                return self._create_connection()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
            except:
                with util.safe_reraise():
                    self._dec_overflow()
                raise
        else:
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
return _ConnectionRecord(self)
       ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 675, in __init__
self.__connect()
^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect
with util.safe_reraise():
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
raise exc_value.with_traceback(exc_tb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect
self.dbapi_connection = connection = pool._invoke_creator(self)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect
return dialect.connect(*cargs, **cparams)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 625, in connect
return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The above exception was the direct cause of the following exception:
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\flask\app.py", line 1536, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\werkzeug\middleware\proxy_fix.py", line 183, in __call__
return self.app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\flask\app.py", line 1514, in wsgi_app
response = self.handle_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\routes\attendance.py", line 47, in index
attendances = query.all()
              ^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 2704, in all
return self._iter().all()  # type: ignore
       ^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 2857, in _iter
result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                              
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
return self._execute_internal(
       
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2241, in _execute_internal
conn = self._connection_for_bind(bind)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2110, in _connection_for_bind
return trans._connection_for_bind(engine, execution_options)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<string>", line 2, in _connection_for_bind
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
ret_value = fn(self, *arg, **kw)
            ^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1189, in _connection_for_bind
conn = bind.connect()
       ^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3273, in connect
return self._connection_cls(self)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 147, in __init__
Connection._handle_dbapi_exception_noconnection(
^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2436, in _handle_dbapi_exception_noconnection
raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
self._dbapi_connection = engine.raw_connection()
                         ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3297, in raw_connection
return self.pool.connect()
       ^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
return _ConnectionFairy._checkout(self)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout
fairy = _ConnectionRecord.checkout(pool)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 713, in checkout
rec = pool._do_get()
      ^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
with util.safe_reraise():
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
raise exc_value.with_traceback(exc_tb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
return self._create_connection()
       ^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
return _ConnectionRecord(self)
       ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 675, in __init__
self.__connect()
^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect
with util.safe_reraise():
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
raise exc_value.with_traceback(exc_tb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect
self.dbapi_connection = connection = pool._invoke_creator(self)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect
return dialect.connect(*cargs, **cparams)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Downloads\nuzum_deployment_20250608_001348\nuzum_deployment_20250608_001348\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 625, in connect
return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
